app/Http/routes.php
<?php
use App\User;
use App\Dies;

Route::get('/', function(){
    
	return redirect('dashboard');
});

Route::get('home', function()
{
    
    return redirect('dashboard');
});

Route::group(['middleware' => 'auth'], function()
{
	
    
    Route::get('dashboard','DashboardController@index');

    Route::resource('users','UsersController');

    Route::group(['middleware' => 'check_location_access'],function(){

        Route::get('location/{location}/dashboard','DashboardController@specific_location');

        Route::get('location/{location}/reports/create/{type}','ReportsController@create');
        Route::get('location/{location}/reports/{report_id}/{action}','ReportsController@show');    
        Route::resource('location.reports','ReportsController');
        
        Route::resource('location.machines','MachinesController');
        Route::resource('location.dies','DiesController');
        Route::resource('location.coins','CoinsController');

        Route::post('location/{location}/managers/{managers}/remove','ManagersController@remove');
        Route::resource('location.managers','ManagersController');

    });

    


});


Route::group(['prefix' => 'admin', 'middleware'=>'admin'], function()
{
    

    Route::get('dashboard','admin\AdminDashboardController@index');  


    Route::post('users/attach','admin\AdminUsersController@attach');
    Route::post('users/{user_id}/remove/{location_id}','admin\AdminUsersController@remove');

    Route::resource('users','admin\AdminUsersController');
    
    Route::resource('companies','admin\AdminCompaniesController');
    Route::resource('rep_companies','admin\AdminRepCompaniesController');
    Route::resource('managing_companies', 'admin\AdminManagingCompaniesController');

    Route::resource('locations','admin\AdminLocationsController');

    Route::get('locations/{location_id}/reports/create/{type}','admin\AdminReportsController@create');
    Route::get('locations/{location_id}/reports/{report_id}/edit','admin\AdminReportsController@edit');    
    Route::get('locations/{location_id}/reports/{report_id}/{action}','admin\AdminReportsController@show');    
    Route::resource('locations.reports','admin\AdminReportsController');    

    Route::resource('machines','admin\AdminMachinesController');
    Route::resource('machine_settings','admin\AdminMachineSettingsController');

    Route::resource('dies','admin\AdminDiesController');
    Route::resource('coins','admin\AdminCoinsController');

    Route::resource('address','admin\AdminAddressesController');
    Route::post('companies/{company_id}/address','admin\AdminAddressesController@addCompanyAddress');
    Route::post('rep_companies/{company_id}/address','admin\AdminAddressesController@addRepCompanyAddress');
    Route::post('managing_companies/{company_id}/address','admin\AdminAddressesController@addManagingCompanyAddress');
    Route::post('locations/{location_id}/address','admin\AdminAddressesController@addLocationAddress');

    Route::get('help',function(){  return view('admin.help'); });
    Route::get('profile', 'admin\AdminUsersController@profile');

    //maybe we could use another AdminLocationPhotoController, 
    //route like locations.photo same as locations.report ...  not sure - fida
    Route::post('locations/{location_id}/addPhoto','admin\AdminLocationsController@addPhoto');
    Route::delete('locations/{location_id}/delPhoto/{photo_id}','admin\AdminLocationsController@delPhoto');
    Route::post('locations/{location_id}/setDefaultPhoto/{photo_id}','admin\AdminLocationsController@setDefaultPhoto');
    
    Route::post('machines/{machine_id}/addPhoto','admin\AdminMachinesController@addPhoto');
    Route::delete('machines/{machine_id}/delPhoto/{photo_id}','admin\AdminMachinesController@delPhoto');
    Route::post('machines/{machine_id}/setDefaultPhoto/{photo_id}','admin\AdminMachinesController@setDefaultPhoto');

    Route::resource('gizmos','admin\parts\gizmos_controller');
    Route::resource('meter_boxes','admin\parts\meter_boxes_controller');
    Route::resource('cc_modems','admin\parts\cc_modems_controller');
    Route::resource('cc_readers','admin\parts\cc_readers_controller');
    Route::resource('bill_validators','admin\parts\bill_validators_controller');
    Route::resource('vaults','admin\parts\vaults_controller');
    Route::resource('hoppers','admin\parts\hoppers_controller');
    Route::resource('touch_screens','admin\parts\touch_screens_controller');

    Route::resource('locations.contracts','admin\AdminContractsController');

    Route::get('get_dies/{location_id}', function($location_id){
        return \DB::table('dies')->where('location_id', $location_id)->get();

    });

    Route::get('get_coins/{location_id}', function($location_id){
        return \DB::table('coins')->where('location_id', $location_id)->get();

    });


	Route::resource('carriers', 'admin\AdminCarriersController');
	Route::resource('programs', 'admin\AdminProgramsController');

    Route::get('device_health','admin\DeviceHealthController@index');
    Route::get('transactions','admin\TransactionsController@index');
    Route::get('device_alerts','admin\DeviceAlertsController@index');
    Route::get('hoppers_report','admin\HoppersReportController@index');


    Route::get('duplicate_device_serial','admin\TestController@duplicate_device_serial');

});



Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);




Route::get('test',function(){

    return $machine = \App\Machine::find(1);


});

resources/views/access_denied.blade.php
<html>
<head>
	<title>Access Denied</title>
</head>
<body style="text-align:center;">
	<h4 style="color:red;margin-top:150px;">Access Denied</h4>

	<a href="/dashboard">dashboard</a>
	<a href="/auth/logout">logout</a>
</body>
</html>

resources/views/dashboard.blade.php
@extends('layout')

@section('main')
   <h1 class="page-header">Dashboard</h1> 
   <p class="text-muted">A dashboard will be displayed here, containing summary of everything with graph etc...</p>
   
@stop

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Dashboard</title>

    <link href="/lib/bootstrap-3.3.2-dist/css/bootstrap.css" rel="stylesheet"> <!-- changed this from min to try to get modal working, didn't get it working-->
    <link href="/lib/bootstrap-3.3.2-dist/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/lib/bootstrap-datepicker/bootstrap-datepicker.css" rel="stylesheet">
    <link href="/lib/bootstrap-clockpicker/bootstrap-clockpicker.css" rel="stylesheet">
    <link href="/lib/alertify/alertify.min.css" rel="stylesheet">
    <link href="/lib/alertify/alertify.default.css" rel="stylesheet">
    <!--
    <link href="//cdn.datatables.net/1.10.5/css/jquery.dataTables.css" rel="stylesheet">
    <link href="//cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
    -->

    <link href="/lib/chosen_v1.4.0/chosen.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/style_manager.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="/lib/jquery-1.11.2.min.js"></script>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="/lib/jquery-2.1.1.min.js"></script>
    <script src="/lib/bootstrap-3.3.2-dist/js/bootstrap.js"></script> <!-- changed this from min to try to get modal working, didn't get it working-->
    <script src="/lib/bootstrap-datepicker/bootstrap-datepicker.js"></script>
    <script src="/lib/bootstrap-clockpicker/bootstrap-clockpicker.js"></script>
    <script src="/js/bootbox-4.4.0.min.js"></script>
    <script src="/lib/alertify/alertify.min.js"></script>
    <script src="/js/holder.js"></script>
    <!--
    <script src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.js"></script>
    <script src="//cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
    -->

    <script src="/lib/geocomplete/jquery.geocomplete.min.js"></script>
    <script src="/lib/chosen_v1.4.0/chosen.jquery.min.js"></script>
    <script src="/js/custom.js"></script>
    <script src="/js/custom_manager.js"></script>

    <script src="/lib/Highcharts/js/highcharts.js"></script>




  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img src="/images/logo_small.gif" alt="my.medallionmint.com"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          
          <h3 class="nav navbar-nav navbar-left top_location_name">{{$location->name}}</h3>
          
          <ul class="nav navbar-nav navbar-right">
            <li><a>{{Auth::user()->name}} <small class="text-muted">{{Auth::user()->role}}</small></a></li>
            <!--
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
            -->
            @if($accessable_locations->count()>1)
            <li>
              <div id="nav_change_location_wrapper">
                {!! Form::select('nav_change_location',$accessable_locations,$location->id,['class'=>'nav_change_location searchable_select']) !!}
              </div>
            </li>
            @endif
          </ul>

        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">         
          


          <ul class="nav nav-sidebar">
            <li {!! (Request::is('*dashboard') ? 'class="active"' : '' ) !!}><a href="/location/{{$location->id}}/dashboard"><i class="glyphicon glyphicon-dashboard"></i>  Dashboard</a></li>
            
            
              <li {!! (Request::is('*reports') ? 'class="active"' : '' ) !!} >
                <a href="{{route('location.reports.index',[$location->id])}}"><i class="glyphicon glyphicon-book"></i> 
                  Reports <span class="badge pull-right">{{$location->report->count()}}</span></a>
              </li>

              <li {!! (Request::is('*managers*') ? 'class="active"' : '' ) !!} >
                <a href="{{route('location.managers.index',[$location->id])}}"><i class="glyphicon glyphicon-user"></i> 
                  Managers <span class="badge pull-right">{{$location->managers->count()}}</span></a>
              </li>  

              <li {!! (Request::is('*machines') ? 'class="active"' : '' ) !!} >
                <a href="{{route('location.machines.index',[$location->id])}}"><i class="glyphicon glyphicon-film"></i> 
                  Machines <span class="badge pull-right">{{$location->machines->count()}}</span></a>
              </li>         

             

              <li {!! (Request::is('*coins') ? 'class="active"' : '' ) !!} >
                <a href="{{route('location.coins.index',[$location->id])}}"><i class="glyphicon glyphicon-copyright-mark"></i> 
                  Coins <span class="badge pull-right">{{$location->coins->count()}}</span>
                </a>
              </li>


              <li {!! (Request::is('*dies') ? 'class="active"' : '' ) !!} >
              <a href="{{route('location.dies.index',[$location->id])}}"><i class="glyphicon glyphicon-record"></i> 
                Dies <span class="badge pull-right">{{$location->dies->count()}}</span>
              </a>
              </li>


            <li><a href="/auth/logout"><i class="glyphicon glyphicon-log-out"></i> Logout</a></li>
          </ul>
         
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">          
         
          @yield('main')      
          
          
         
        </div>
      </div>
    </div>


  </body>
</html>

@if(Session::has('flash_message'))
    <?php echo "<script>alertify.success('". session('flash_message'). "');</script>"; ?>
@endif

<script>
    //$('.table_sortable').DataTable();
</script>

@yield('script')

resources/views/no_permission.blade.php
<html>
<head>
	<title>No Permission Yet!</title>
</head>
<body>
	<h4>Sorry {{$user->name}} <small class="text-muted">{{$user->role}}</small></h4>
	
	@if($user->role == 'location_manager')
		<p>You don't have permission to see any location info</p>
	@elseif($user->role == 'company_manager')
		<p>No location found at your company -> {{$user->companies->first()->name}}</p>
	@endif


	<a href="/auth/logout">logout</a>
</body>
</html>