app/Http/routes.php
<?php
use App\User;
use App\Dies;

Route::get('/', function(){
    
	return redirect('dashboard');
});

Route::get('home', function()
{
    
    return redirect('dashboard');
});

Route::group(['middleware' => 'auth'], function()
{
	
    
    Route::get('dashboard','DashboardController@index');

    Route::resource('users','UsersController');

    Route::group(['middleware' => 'check_location_access'],function(){

        Route::get('location/{location}/dashboard','DashboardController@specific_location');

        Route::get('location/{location}/reports/create/{type}','ReportsController@create');
        Route::get('location/{location}/reports/{report_id}/{action}','ReportsController@show');    
        Route::resource('location.reports','ReportsController');
        
        Route::resource('location.machines','MachinesController');
        Route::resource('location.dies','DiesController');
        Route::resource('location.coins','CoinsController');

        Route::post('location/{location}/managers/{managers}/remove','ManagersController@remove');
        Route::resource('location.managers','ManagersController');

    });

    


});


Route::group(['prefix' => 'admin', 'middleware'=>'admin'], function()
{
    

    Route::get('dashboard','admin\AdminDashboardController@index');  


    Route::post('users/attach','admin\AdminUsersController@attach');
    Route::post('users/{user_id}/remove/{location_id}','admin\AdminUsersController@remove');

    Route::resource('users','admin\AdminUsersController');
    
    Route::resource('companies','admin\AdminCompaniesController');
    Route::resource('rep_companies','admin\AdminRepCompaniesController');
    Route::resource('managing_companies', 'admin\AdminManagingCompaniesController');

    Route::resource('locations','admin\AdminLocationsController');

    Route::get('locations/{location_id}/reports/create/{type}','admin\AdminReportsController@create');
    Route::get('locations/{location_id}/reports/{report_id}/edit','admin\AdminReportsController@edit');    
    Route::get('locations/{location_id}/reports/{report_id}/{action}','admin\AdminReportsController@show');    
    Route::resource('locations.reports','admin\AdminReportsController');    

    Route::resource('machines','admin\AdminMachinesController');
    Route::resource('machine_settings','admin\AdminMachineSettingsController');

    Route::resource('dies','admin\AdminDiesController');
    Route::resource('coins','admin\AdminCoinsController');

    Route::resource('address','admin\AdminAddressesController');
    Route::post('companies/{company_id}/address','admin\AdminAddressesController@addCompanyAddress');
    Route::post('rep_companies/{company_id}/address','admin\AdminAddressesController@addRepCompanyAddress');
    Route::post('managing_companies/{company_id}/address','admin\AdminAddressesController@addManagingCompanyAddress');
    Route::post('locations/{location_id}/address','admin\AdminAddressesController@addLocationAddress');

    Route::get('help',function(){  return view('admin.help'); });
    Route::get('profile', 'admin\AdminUsersController@profile');

    //maybe we could use another AdminLocationPhotoController, 
    //route like locations.photo same as locations.report ...  not sure - fida
    Route::post('locations/{location_id}/addPhoto','admin\AdminLocationsController@addPhoto');
    Route::delete('locations/{location_id}/delPhoto/{photo_id}','admin\AdminLocationsController@delPhoto');
    Route::post('locations/{location_id}/setDefaultPhoto/{photo_id}','admin\AdminLocationsController@setDefaultPhoto');
    
    Route::post('machines/{machine_id}/addPhoto','admin\AdminMachinesController@addPhoto');
    Route::delete('machines/{machine_id}/delPhoto/{photo_id}','admin\AdminMachinesController@delPhoto');
    Route::post('machines/{machine_id}/setDefaultPhoto/{photo_id}','admin\AdminMachinesController@setDefaultPhoto');

    Route::resource('gizmos','admin\parts\gizmos_controller');
    Route::resource('meter_boxes','admin\parts\meter_boxes_controller');
    Route::resource('cc_modems','admin\parts\cc_modems_controller');
    Route::resource('cc_readers','admin\parts\cc_readers_controller');
    Route::resource('bill_validators','admin\parts\bill_validators_controller');
    Route::resource('vaults','admin\parts\vaults_controller');
    Route::resource('hoppers','admin\parts\hoppers_controller');
    Route::resource('touch_screens','admin\parts\touch_screens_controller');

    Route::resource('locations.contracts','admin\AdminContractsController');

    Route::get('get_dies/{location_id}', function($location_id){
        return \DB::table('dies')->where('location_id', $location_id)->get();

    });

    Route::get('get_coins/{location_id}', function($location_id){
        return \DB::table('coins')->where('location_id', $location_id)->get();

    });


	Route::resource('carriers', 'admin\AdminCarriersController');
	Route::resource('programs', 'admin\AdminProgramsController');

    Route::get('device_health','admin\DeviceHealthController@index');
    Route::get('transactions','admin\TransactionsController@index');
    Route::get('device_alerts','admin\DeviceAlertsController@index');
    Route::get('hoppers_report','admin\HoppersReportController@index');


    Route::get('duplicate_device_serial','admin\TestController@duplicate_device_serial');

});



Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);




Route::get('test',function(){

    return $machine = \App\Machine::find(1);


});

app/Http/Controllers/admin/TransactionsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Transaction;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class TransactionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $today = date('Y-m-d');
        //$today = date('2016-12-21');
        $today_transactions = Transaction::where('transaction_time','>=',$today)->get();

        $today_summary = array();

        $today_summary['total_amount'] = $today_transactions->sum('total_amount');
        $today_summary['total_cc_amount'] = $today_transactions->where('transaction_type','R')->sum('total_amount');
        $today_summary['total_cash_amount'] = $today_transactions->where('transaction_type','C')->sum('total_amount');
        $today_summary['total_coins'] = $today_transactions->sum('items');
        $today_summary['total_transactions'] = $today_transactions->groupBy('transaction_ref')->count();

        if($today_summary['total_amount']){
            $today_summary['cc_percent'] = round( $today_summary['total_cc_amount'] / $today_summary['total_amount'] * 100 );
            $today_summary['cash_percent'] = round( $today_summary['total_cash_amount'] / $today_summary['total_amount'] * 100 );
        }else{
            $today_summary['cc_percent'] = 0;
            $today_summary['cash_percent'] = 0;
        }

        if($today_summary['total_coins']){
            $today_summary['per_trans'] = round($today_summary['total_amount'] / $today_summary['total_coins']);
        }else{
            $today_summary['per_trans'] = 0;
        }

        //return $today_summary;

        $transactions = Transaction::with(['machine'=>function($query){
            $query->with('location');

        },'coin'])->orderBy('transaction_time','desc')->paginate(100);

        return view('admin.transactions.index',compact('transactions','today_summary'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/transactions/index.blade.php
@extends('admin.layout')

@section('title','Transactions')

@section('main')

    <h3 class="page-header">
        Transactions <small class="text-muted" title="m-d-Y">{{date('m-d-Y, h:i A')}}</small>
    </h3>

    <h4>Total for today {{date('m-d-Y')}}:
        <strong>{{$today_summary['total_transactions']}}</strong> Transactions,
        <strong>${{$today_summary['total_cc_amount']}}</strong> CC <span class="text-muted">({{$today_summary['cc_percent']}}%)</span>,
        <strong>${{$today_summary['total_cash_amount']}}</strong> Cash <span class="text-muted">({{$today_summary['cash_percent']}}%)</span>,
        <strong>{{$today_summary['total_coins']}}</strong> Coins <span class="text-muted">({{$today_summary['per_trans']}}/per trans)</span>,
    </h4>



    <table class="table table-bordered table-striped">

        <thead>
            <tr>
                <th>SL</th>
                <th>Reference</th>
                <th>Location</th>
                <th>Machine</th>
                <th>Coin</th>
                <th>Device</th>
                <th>Type</th>
                <th>Card Number</th>
                <th>Amount</th>
                <th>Time</th>
            </tr>
        </thead>

        <tbody>

            <?php $sl = $transactions->firstItem();?>

            @foreach($transactions as $index=>$transaction)

                <tr>
                    <td>{{$sl++}}</td>
                    <td>{{$transaction->transaction_ref}}</td>
                    <td>
                        @if(isset($transaction->machine->location))
                            <a href="{{URL::route('admin.locations.edit',$transaction->machine->location->id)}}">
                                {{$transaction->machine->location->name}}
                            </a>

                        @else
                            Not Found
                        @endif
                    </td>
                    <td>
                        @if(isset($transaction->machine))
                            <a href="{{URL::route('admin.machines.edit',$transaction->machine->id)}}">
                                {{$transaction->machine->name}}
                            </a>

                        @else
                            Not Found
                        @endif
                    </td>
                    <td>
                        @if($transaction->coin)
                            {{(int) $transaction->item_number.' '.$transaction->coin->name}}
                        @else
                            {{$transaction->item_number}}
                        @endif
                    </td>

                    <td>{{$transaction->device_serial}}</td>
                    <td>
                        @if($transaction->transaction_type == 'C')
                            <i class="fa fa-money text-primary" aria-hidden="true" title="Cash"></i>
                        @elseif($transaction->transaction_type == 'R')
                            <i class="fa fa-credit-card text-danger" aria-hidden="true" title="Credit Card "></i>
                        @elseif($transaction->transaction_type == 'P')
                            <i class="fa fa-user-md text-muted" aria-hidden="true" title="Test Pass"></i>
                        @endif
                    </td>
                    <td>{{$transaction->card_num}}</td>
                    <td>{{$transaction->total_amount}}</td>
                    <td>{{date('m-d-Y h:i A',strtotime($transaction->transaction_time))}}</td>
                </tr>

            @endforeach
        </tbody>
    </table>

    {!! $transactions->render() !!}


@stop

@section('script')

@stop