app/Http/routes.php
<?php
use App\User;
use App\Dies;

Route::get('/', function(){
    
	return redirect('dashboard');
});

Route::get('home', function()
{
    
    return redirect('dashboard');
});

Route::group(['middleware' => 'auth'], function()
{
	
    
    Route::get('dashboard','DashboardController@index');

    Route::resource('users','UsersController');

    Route::group(['middleware' => 'check_location_access'],function(){

        Route::get('location/{location}/dashboard','DashboardController@specific_location');

        Route::get('location/{location}/reports/create/{type}','ReportsController@create');
        Route::get('location/{location}/reports/{report_id}/{action}','ReportsController@show');    
        Route::resource('location.reports','ReportsController');
        
        Route::resource('location.machines','MachinesController');
        Route::resource('location.dies','DiesController');
        Route::resource('location.coins','CoinsController');

        Route::post('location/{location}/managers/{managers}/remove','ManagersController@remove');
        Route::resource('location.managers','ManagersController');

    });

    


});


Route::group(['prefix' => 'admin', 'middleware'=>'admin'], function()
{
    

    Route::get('dashboard','admin\AdminDashboardController@index');  


    Route::post('users/attach','admin\AdminUsersController@attach');
    Route::post('users/{user_id}/remove/{location_id}','admin\AdminUsersController@remove');

    Route::resource('users','admin\AdminUsersController');
    
    Route::resource('companies','admin\AdminCompaniesController');
    Route::resource('rep_companies','admin\AdminRepCompaniesController');
    Route::resource('managing_companies', 'admin\AdminManagingCompaniesController');

    Route::resource('locations','admin\AdminLocationsController');

    Route::get('locations/{location_id}/reports/create/{type}','admin\AdminReportsController@create');
    Route::get('locations/{location_id}/reports/{report_id}/edit','admin\AdminReportsController@edit');    
    Route::get('locations/{location_id}/reports/{report_id}/{action}','admin\AdminReportsController@show');    
    Route::resource('locations.reports','admin\AdminReportsController');    

    Route::resource('machines','admin\AdminMachinesController');
    Route::resource('machine_settings','admin\AdminMachineSettingsController');

    Route::resource('dies','admin\AdminDiesController');
    Route::resource('coins','admin\AdminCoinsController');

    Route::resource('address','admin\AdminAddressesController');
    Route::post('companies/{company_id}/address','admin\AdminAddressesController@addCompanyAddress');
    Route::post('rep_companies/{company_id}/address','admin\AdminAddressesController@addRepCompanyAddress');
    Route::post('managing_companies/{company_id}/address','admin\AdminAddressesController@addManagingCompanyAddress');
    Route::post('locations/{location_id}/address','admin\AdminAddressesController@addLocationAddress');

    Route::get('help',function(){  return view('admin.help'); });
    Route::get('profile', 'admin\AdminUsersController@profile');

    //maybe we could use another AdminLocationPhotoController, 
    //route like locations.photo same as locations.report ...  not sure - fida
    Route::post('locations/{location_id}/addPhoto','admin\AdminLocationsController@addPhoto');
    Route::delete('locations/{location_id}/delPhoto/{photo_id}','admin\AdminLocationsController@delPhoto');
    Route::post('locations/{location_id}/setDefaultPhoto/{photo_id}','admin\AdminLocationsController@setDefaultPhoto');
    
    Route::post('machines/{machine_id}/addPhoto','admin\AdminMachinesController@addPhoto');
    Route::delete('machines/{machine_id}/delPhoto/{photo_id}','admin\AdminMachinesController@delPhoto');
    Route::post('machines/{machine_id}/setDefaultPhoto/{photo_id}','admin\AdminMachinesController@setDefaultPhoto');

    Route::resource('gizmos','admin\parts\gizmos_controller');
    Route::resource('meter_boxes','admin\parts\meter_boxes_controller');
    Route::resource('cc_modems','admin\parts\cc_modems_controller');
    Route::resource('cc_readers','admin\parts\cc_readers_controller');
    Route::resource('bill_validators','admin\parts\bill_validators_controller');
    Route::resource('vaults','admin\parts\vaults_controller');
    Route::resource('hoppers','admin\parts\hoppers_controller');
    Route::resource('touch_screens','admin\parts\touch_screens_controller');

    Route::resource('locations.contracts','admin\AdminContractsController');

    Route::get('get_dies/{location_id}', function($location_id){
        return \DB::table('dies')->where('location_id', $location_id)->get();

    });

    Route::get('get_coins/{location_id}', function($location_id){
        return \DB::table('coins')->where('location_id', $location_id)->get();

    });


	Route::resource('carriers', 'admin\AdminCarriersController');
	Route::resource('programs', 'admin\AdminProgramsController');

    Route::get('device_health','admin\DeviceHealthController@index');
    Route::get('transactions','admin\TransactionsController@index');
    Route::get('device_alerts','admin\DeviceAlertsController@index');
    Route::get('hoppers_report','admin\HoppersReportController@index');


    Route::get('duplicate_device_serial','admin\TestController@duplicate_device_serial');

});



Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);




Route::get('test',function(){

    return $machine = \App\Machine::find(1);


});

app/Company.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{


    protected $fillable = ['name','time_zone_id','carrier_id','shipper_no','term_id','website','notes','active'];

    public function managers(){
        return $this->hasMany('App\User','company_managers');
    }

    public function locations(){

        return $this->hasMany('App\Location');
    }

    public function machines(){

        return $this->hasManyThrough('App\Machine','App\Location');
    }

    public function term(){
        return $this->belongsTo('App\Term');
    }

    public function carrier(){
        return $this->belongsTo('App\Carrier');
    }

    public function time_zone(){
        return $this->belongsTo('App\TimeZone');
    }

    public function setTermIdAttribute($value){

        if($value==''){
            $value=null;
        }

        $this->attributes['term_id'] = $value;
    }

    public function setCarrierIdAttribute($value){
        if($value == '' ){
            $value = null;
        }
        $this->attributes['carrier_id'] = $value ;
    }

    public function setTimeZoneIdAttribute($value){
        if($value == '' ){
            $value = null;
        }
        $this->attributes['time_zone_id'] = $value ;
    }

    public function addresses(){
        return $this->morphMany('App\Address', 'addressable');
    }

}

resources/views/admin/companies/create.blade.php
@extends('admin.layout')

@section('title','Add New Parent Company')

@section('main')
   <h1 class="page-header">Add New Parent Company</h1>
   @include('partial.form_error')

   {!! Form::open(['url'=>'admin/companies','class'=>'row form-horizontal']) !!}

      @include('admin.companies.form',['submit_btn_text'=>'Add New Parent Company'])

   {!!Form::close()!!}


@stop

@section('script')
   @include('admin.companies.script')
@stop

resources/views/admin/companies/edit.blade.php
@extends('admin.layout')
@section('title','Edit '.$company->name)

@section('main')
   <a class="btn btn-sm btn-info pull-right" href="{{URL::route('admin.companies.show',$company->id)}}">
      <i class="glyphicon glyphicon-eye-open"></i> View Details
   </a>
   <h1 class="page-header">
      Edit {{ $company->name }}
   </h1>
      @include('partial.form_error')

   {!! Form::model($company,['method'=>'PATCH','url' => ['admin/companies',$company->id ],'files'=>'true', 'class'=>'row form-horizontal edit']) !!}

      @include('admin.companies.form',['submit_btn_text'=>'Update Parent Company'])

   {!!Form::close()!!}

@stop


@section('script')
   @include('admin.companies.script')
@stop

resources/views/admin/companies/form.blade.php
<div class="col-sm-6">

	<div class="form-group">
		{!!Form::label('name','Parent Company Name',array('class'=>'control-label col-xs-5'))!!}
		<div class="col-xs-7 @if ($errors->has('name')) has-error @endif">
			{!!Form::text('name',null,array('class'=>'form-control')) !!}
			@if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif
		</div>
	</div>

	<div class="form-group">
		{!!Form::label('term_id','Terms',array('class'=>'control-label col-xs-5'))!!}
		<div class="col-xs-7">
			{!!Form::select('term_id',array(null=>'Please Select')+$terms,null,array('class'=>'form-control searchable_select')) !!}
		</div>
	</div>

	<div class="form-group">
		{!!Form::label('carrier_id','Preferred Carrier',array('class'=>'control-label col-xs-5'))!!}
		<div class="col-xs-7">
			{!!Form::select('carrier_id',array(null=>'Please Select')+$carriers,null,array('class'=>'form-control')) !!}
		</div>
	</div>

	<div class="form-group">
		{!!Form::label('shipper_no','Shipper Number',array('class'=>'control-label col-xs-5'))!!}
		<div class="col-xs-7">
			{!!Form::text('shipper_no',null,array('class'=>'form-control')) !!}
		</div>
	</div>

	<div class="form-group">
		{!!Form::label('time_zone_id','Time Zone',array('class'=>'control-label col-xs-5'))!!}
		<div class="col-xs-7">
			{!!Form::select('time_zone_id',array(null=>'Please Select')+$time_zones,null,array('class'=>'form-control')) !!}
		</div>
	</div>

	<div class="form-group">
		{!!Form::label('website','Website',array('class'=>'control-label col-xs-5'))!!}
		<div class="col-xs-7">
			{!!Form::text('website',null,array('class'=>'form-control')) !!}
		</div>
	</div>

	<div class="form-group">
		{!!Form::label('notes','Notes',array('class'=>'control-label col-xs-5'))!!}
		<div class="col-xs-7">
			{!!Form::textarea('notes',null,array('class'=>'form-control', 'rows' => 3)) !!}
		</div>
	</div>

	<div class="form-group">
		{!!Form::label('active','Active',array('class'=>'control-label col-xs-5'))!!}
		<div class="col-xs-7">
			<div class="make-switch" data-on="success" data-off="danger" data-on-label="Yes" data-off-label="No">
				{!!Form::checkbox('active',1,true,array('class'=>'checkbox')) !!}
			</div>
		</div>
	</div>

	<div class="form-group">
		<div class="col-xs-offset-5 col-xs-7">

			{!! Form::submit($submit_btn_text,['class'=>'btn btn-primary']) !!}

			@if(Request::is('admin/companies/*/edit'))
				<a href="{{ URL::route('admin.companies.show', $company->id) }}" class="btn btn-default"><i class="glyphicon glyphicon-remove"></i> Cancel</a>
			@elseif(Request::is('admin/companies/create'))
				<a href="{{ URL::route('admin.companies.index') }}" class="btn btn-default"><i class="glyphicon glyphicon-remove"></i> Cancel</a>
			@endif


		</div>

	</div>

</div>

resources/views/admin/companies/index.blade.php
@extends('admin.layout')
@section('title','Parent Companies')

@section('main')

   <h1 class="page-header">Parent Companies
	   <a href="{{URL::to('admin/companies/create')}}" class="btn btn-sm btn-primary pull-right">
		   <i class="glyphicon glyphicon-plus"></i> Add New Parent Company
	   </a>
   </h1>

   @if(!count($companies))

           <p class="alert alert-warning">
               No parent companies found! Please
               <a href="{{ url('admin/companies/create')}}">create a parent company</a>
           </p>
   @else

   	<?php $sl = 1; ?>
   	<table class="table table-striped table-bordered table_sortable" id="parent_companies_index">
        <thead>
            <tr><th>SL</th><th>Parent Company Name</th><th>Locations</th><th>Machines</th><th>Action</th></tr>
        </thead>
	   	@foreach($companies as $index=>$company)
	   	<tr>
	   		<td>{{1+$index++}}</td>
	   		<td>
	   			<a href="{{ URL::route('admin.companies.show',$company->id) }}">{{$company->name}}</a>
	   			
	   		</td>	
	   		<td>{{ $company->locations->count() }}</td>
	   		<td>{{ $company->machines->count() }}</td>

	   		<td>
	   			
	   			<a href="{{ URL::route('admin.companies.edit',$company->id) }}" class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> Edit</a>&nbsp;&nbsp;
				<a title="delete" data-url="{{url('admin/companies/'.$company->id)}}" data-token="{{csrf_token()}}" class="admin_company_del_btn btn btn-xs btn-danger" href="#"><i class="glyphicon glyphicon-trash"></i> Delete</a> 

	   		</td>
	   	</tr>
	   	@endforeach
   	</table>

   @endif

@stop

@section('script')
  @include('admin.companies.script')
@stop

resources/views/admin/companies/script.blade.php
<script>
	$(document).ready(function() {



        $('.admin_company_del_btn').click(function(e){
            e.preventDefault();

            var target = $(this);
            var url = $(this).data('url');
            var token = $(this).data('token');




            alertify.confirm('Are you sure you want to delete this parent company? This action cannot be undone.').setting({
                'title':'<span class="glyphicon glyphicon-trash"></span> Delete Parent Company',
                'labels':{ok:'DELETE'},
                'onok': function(){

                    $.ajax({

                        url: url,
                        type: 'POST',
                        data: {_method: 'delete', _token: token},

                        beforeSend:function(){

                            $(target).addClass('disabled');
                            $(target).parent().parent().css('opacity','.5');

                        },
                        success: function (res) {

                            if(res=='success'){

                                $(target).parent().parent().fadeOut(500,function(){
                                    $(target).parent().parent().remove();
                                });

                                alertify.success('Company has been deleted');
                                $('.nav-sidebar .badge.company').html(parseInt($('.nav-sidebar .badge.company').html())-1);

                            }else{

                                $(target).removeClass('disabled');
                                $(target).parent().parent().css('opacity','1');
                                alertify.error('Failed to delete company. <br>'+res);
                            }


                        }
                    });


                },
                'oncancel':function(){


                }
            });
        });



    });
</script>

resources/views/admin/companies/show.blade.php
@extends('admin.layout')
@section('title',$company->name)

@section('main')
    <h1 class="page-header">{{ $company->name }}
        <a href="{{ URL::route('admin.companies.edit',$company->id) }}" class="btn btn-sm btn-info pull-right"><i class="glyphicon glyphicon-edit"></i> Edit</a>&nbsp;&nbsp;
    </h1>

    <div class="form-group">
        @include('partial.form_error')
    </div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#details" aria-controls="details" role="tab" data-toggle="tab">Details</a></li>
        <li role="presentation" ><a href="#locations" aria-controls="locations" role="tab" data-toggle="tab">Locations ({{$company->locations->count()}})</a></li>
        <li role="presentation" ><a href="#address" aria-controls="address" role="tab" data-toggle="tab">Address ({{$company->addresses->count()}})</a></li>
    </ul>


    <div class="tab-content">

        <div role="tabpanel" class="tab-pane active" id="details">
            <table class="table table-striped">

                <tr>
                    <td>Term</td>
                    <td>
                        @if($company->term)
                            {{$company->term->name}}
                        @endif
                    </td>
                </tr>
                <tr>
                    <td>Preferred Carrier</td>
                    <td>
                        @if($company->carrier)
                            {{$company->carrier->name}}
                        @endif
                    </td>
                </tr>
                <tr>
                    <td>Shipper #</td>
                    <td>{{$company->shipper_no}}</td>
                </tr>
                <tr>
                    <td>Time Zone</td>
                    <td>
                        @if($company->time_zone)
                            {{$company->time_zone->name}}
                        @endif
                    </td>
                </tr>
                <tr><td>Website</td><td>{{$company->website}}</td></tr>
                <tr>
                    <td>Notes</td>
                    <td>{{$company->notes}}</td>
                </tr>

                <tr><td>Status</td><td>{{$company->active ? 'Active' :'InActive'}}</td></tr>
            </table>
        </div>

        <div role="tabpanel" class="tab-pane" id="locations">
            <table class="table table-bordered ">
                <thead>
                <tr>
                    <th>SL</th>
                    <th>Location Name</th>
                </tr>
                </thead>

                <tbody>

                @foreach($company->locations as $index=>$location)
                    <tr>
                        <td>{{$index+1}}</td>
                        <td><a href="/admin/locations/{{$location->id}}">{{$location->name}}</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

        <div role="tabpanel" class="tab-pane" id="address">

            @include('admin.address.index',[
                'path'=>'admin/companies/'.$company->id.'/address#address',
                'addresses' => $company->addresses

                ])

        </div>

    </div>

    @include('admin.address.modal')


@stop

@section('script')
    @include('admin.companies.script')
    @include('admin.address.script')
@stop