app/Http/routes.php
<?php
use App\User;
use App\Dies;

Route::get('/', function(){
    
	return redirect('dashboard');
});

Route::get('home', function()
{
    
    return redirect('dashboard');
});

Route::group(['middleware' => 'auth'], function()
{
	
    
    Route::get('dashboard','DashboardController@index');

    Route::resource('users','UsersController');

    Route::group(['middleware' => 'check_location_access'],function(){

        Route::get('location/{location}/dashboard','DashboardController@specific_location');

        Route::get('location/{location}/reports/create/{type}','ReportsController@create');
        Route::get('location/{location}/reports/{report_id}/{action}','ReportsController@show');    
        Route::resource('location.reports','ReportsController');
        
        Route::resource('location.machines','MachinesController');
        Route::resource('location.dies','DiesController');
        Route::resource('location.coins','CoinsController');

        Route::post('location/{location}/managers/{managers}/remove','ManagersController@remove');
        Route::resource('location.managers','ManagersController');

    });

    


});


Route::group(['prefix' => 'admin', 'middleware'=>'admin'], function()
{
    

    Route::get('dashboard','admin\AdminDashboardController@index');  


    Route::post('users/attach','admin\AdminUsersController@attach');
    Route::post('users/{user_id}/remove/{location_id}','admin\AdminUsersController@remove');

    Route::resource('users','admin\AdminUsersController');
    
    Route::resource('companies','admin\AdminCompaniesController');
    Route::resource('rep_companies','admin\AdminRepCompaniesController');
    Route::resource('managing_companies', 'admin\AdminManagingCompaniesController');

    Route::resource('locations','admin\AdminLocationsController');

    Route::get('locations/{location_id}/reports/create/{type}','admin\AdminReportsController@create');
    Route::get('locations/{location_id}/reports/{report_id}/edit','admin\AdminReportsController@edit');    
    Route::get('locations/{location_id}/reports/{report_id}/{action}','admin\AdminReportsController@show');    
    Route::resource('locations.reports','admin\AdminReportsController');    

    Route::resource('machines','admin\AdminMachinesController');
    Route::resource('machine_settings','admin\AdminMachineSettingsController');

    Route::resource('dies','admin\AdminDiesController');
    Route::resource('coins','admin\AdminCoinsController');

    Route::resource('address','admin\AdminAddressesController');
    Route::post('companies/{company_id}/address','admin\AdminAddressesController@addCompanyAddress');
    Route::post('rep_companies/{company_id}/address','admin\AdminAddressesController@addRepCompanyAddress');
    Route::post('managing_companies/{company_id}/address','admin\AdminAddressesController@addManagingCompanyAddress');
    Route::post('locations/{location_id}/address','admin\AdminAddressesController@addLocationAddress');

    Route::get('help',function(){  return view('admin.help'); });
    Route::get('profile', 'admin\AdminUsersController@profile');

    //maybe we could use another AdminLocationPhotoController, 
    //route like locations.photo same as locations.report ...  not sure - fida
    Route::post('locations/{location_id}/addPhoto','admin\AdminLocationsController@addPhoto');
    Route::delete('locations/{location_id}/delPhoto/{photo_id}','admin\AdminLocationsController@delPhoto');
    Route::post('locations/{location_id}/setDefaultPhoto/{photo_id}','admin\AdminLocationsController@setDefaultPhoto');
    
    Route::post('machines/{machine_id}/addPhoto','admin\AdminMachinesController@addPhoto');
    Route::delete('machines/{machine_id}/delPhoto/{photo_id}','admin\AdminMachinesController@delPhoto');
    Route::post('machines/{machine_id}/setDefaultPhoto/{photo_id}','admin\AdminMachinesController@setDefaultPhoto');

    Route::resource('gizmos','admin\parts\gizmos_controller');
    Route::resource('meter_boxes','admin\parts\meter_boxes_controller');
    Route::resource('cc_modems','admin\parts\cc_modems_controller');
    Route::resource('cc_readers','admin\parts\cc_readers_controller');
    Route::resource('bill_validators','admin\parts\bill_validators_controller');
    Route::resource('vaults','admin\parts\vaults_controller');
    Route::resource('hoppers','admin\parts\hoppers_controller');
    Route::resource('touch_screens','admin\parts\touch_screens_controller');

    Route::resource('locations.contracts','admin\AdminContractsController');

    Route::get('get_dies/{location_id}', function($location_id){
        return \DB::table('dies')->where('location_id', $location_id)->get();

    });

    Route::get('get_coins/{location_id}', function($location_id){
        return \DB::table('coins')->where('location_id', $location_id)->get();

    });


	Route::resource('carriers', 'admin\AdminCarriersController');
	Route::resource('programs', 'admin\AdminProgramsController');

    Route::get('device_health','admin\DeviceHealthController@index');
    Route::get('transactions','admin\TransactionsController@index');
    Route::get('device_alerts','admin\DeviceAlertsController@index');
    Route::get('hoppers_report','admin\HoppersReportController@index');


    Route::get('duplicate_device_serial','admin\TestController@duplicate_device_serial');

});



Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);




Route::get('test',function(){

    return $machine = \App\Machine::find(1);


});

app/Coin.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Coin extends Model {

    protected $fillable = [
        'active',
        'name',
        'location_id',
        'top_inventory',
        'inventory',
        'notes',
        'metal',
        'finish',
        'front_dies_type',
        'back_dies_type',
        'front_dies',
        'back_dies'
    ];

    public function location(){

        return $this->belongsTo('App\Location');
    }
    public function front_dies(){

        return Dies::where('id','=',$this->front_dies)->first();
    }

    public function back_dies(){

        return Dies::where('id','=',$this->back_dies)->first();
    }

    /*public function machine(){
        return $this->hasMany('App\Machine','coin_1');
    }*/

}

app/Http/Controllers/CoinsController.php
<?php namespace App\Http\Controllers;

use App\Location;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class CoinsController extends Controller {

	
	public function index($location_id)
    {
        
        $location = Location::findOrFail($location_id);
        $coins = $location->coins;
        
        return view('coins.index',compact('coins','location')); 
    }


}

resources/views/admin/coins/create.blade.php
@extends('admin.layout')

@section('main')
    <h1 class="page-header">Add New Coin</h1>
    <div class="row">
        {!! Form::open(['url'=>'admin/coins','class'=>'col-sm-12 col-lg-6']) !!}
        @include('admin.coins.form',['submit_btn_text'=>'Add New Coin'])
        {!! Form::close() !!}
    </div>

@stop

@section('script')
	@include('admin.coins.script')
@stop

resources/views/admin/coins/edit.blade.php
@extends('admin.layout')

@section('main')
    <h1 class="page-header">Edit Coin - {{ $coin->name }}</h1>

    <div class="row">

        {!! Form::model($coin,['method'=>'PATCH','url' => ['admin/coins',$coin->id ], 'class'=>'col-sm-12 col-lg-6 edit']) !!}

        @include('admin.coins.form',['submit_btn_text'=>'Update Coin Info'])


        {!!Form::close()!!}
    </div>

@stop


@section('script')
	@include('admin.coins.script')
@stop

resources/views/admin/coins/form.blade.php
<div class="form-group">

    @include('partial.form_error')

</div>

<div class="row">
    <div class="col-sm-5">
        <div class="form-group">

            {!! Form::label('name','Coin Name') !!}
            <div class="@if ($errors->has('name')) has-error @endif">
                {!! Form::text('name',null,array('class'=>'form-control') ) !!}
                @if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif
            </div>

        </div>

        <div class="form-group">
            <div class="@if ($errors->has('location_id')) has-error @endif">
                {!! Form::label('location_id','Location') !!}
                {!! Form::select('location_id',$locations,null,array('class'=>'form-control searchable_select') ) !!}
                @if ($errors->has('location_id')) <p class="help-block">{{ $errors->first('location_id') }}</p> @endif
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('top_inventory','Top Inventory') !!}
            {!! Form::text('top_inventory',null,array('class'=>'form-control') ) !!}
        </div>

        <div class="form-group">
            {!! Form::label('inventory','Inventory') !!}
            {!! Form::text('inventory',null,array('class'=>'form-control') ) !!}
        </div>



        <div class="form-group">
            {!! Form::label('notes','Notes') !!}
            {!! Form::textarea('notes',null,array('class'=>'form-control','rows'=>'2') ) !!}
        </div>

        <div class="form-group">
        {!!Form::label('active','Active',array('class'=>'control-label'))!!}
            <div class="make-switch" data-on="primary" data-off="info" data-on-label="Yes" data-off-label="No">
                {!!Form::checkbox('active',1,true,array('class'=>'checkbox')) !!}
            </div>
        </div>


    </div>

    <div class="col-sm-7">
        <div class="row">
            <div class="col-sm-6 form-group">

                {!! Form::label('metal','Metal') !!}
                {!! Form::select('metal',array(
                'Brass'=>'Brass',
                'Copper'=>'Copper',
                'Nickel Silver'=>'Nickel Silver'
                ),null,array('class'=>'form-control') ) !!}
            </div>

            <div class="col-sm-6 form-group">
                {!! Form::label('finish','Finish') !!}
                {!! Form::select('finish',array(
                'Shiny'=>'Shiny',
                'Antique'=>'Antique'
                ),null,array('class'=>'form-control') ) !!}
            </div>
        </div>


        <div class="row">
            <div class="col-sm-6 form-group">
                {!! Form::label('front_dies_type','Front Dies Type') !!}
                {!! Form::select('front_dies_type',array(
                'Location Dies'=>'Location Dies',
                'Stock Dies'=>'Stock Dies'
                ),null,array('class'=>'form-control') ) !!}

            </div>

            <div class="col-sm-6 form-group">
                {!! Form::label('back_dies_type','Back Dies Type') !!}
                {!! Form::select('back_dies_type',array(
                'Location Dies'=>'Location Dies',
                'Stock Dies'=>'Stock Dies'
                ),null,array('class'=>'form-control') ) !!}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6 form-group">
                {!! Form::label('front_dies','Front Dies') !!}

                @if(isset($coin->front_dies_type))
                    @if($coin->front_dies_type == 'Location Dies')
                        <select name="front_dies" id="front_dies" class="form-control">
                            <option value="">Please Select</option>
                            @foreach($location_dies as $dies)
                                <option
                                    value="{{ $dies->id }}"
                                    data-imagesrc="{{ $dies->photo}}"
                                    {{ ($dies->id == $coin->front_dies ? 'selected':'') }}
                                    >{{$dies->name}}</option>

                            @endforeach
                        </select>
                    @else
                        <select name="front_dies" id="front_dies" class="form-control">
                            <option value="">Please Select</option>
                            @foreach($stock_dies as $dies)
                                <option
                                    value="{{ $dies->id }}"
                                    data-imagesrc="{{ $dies->photo}}"
                                    {{ ($dies->id == $coin->front_dies ? 'selected':'') }}
                                    >{{$dies->name}}</option>

                            @endforeach
                        </select>
                    @endif
                @else
                    {!! Form::select('front_dies',array(),null,array('class'=>'form-control') ) !!}
                @endif



                @if(isset($coin->metal))
                    <div class="dies front {!! strtolower($coin->metal) !!}">
                        <img src="/upload/100-{!! $coin->front_dies()->photo !!}">

                    </div>
                @else
                    <div class="dies front brass">		</div>
                @endif



            </div>

            <div class="col-sm-6 form-group">
                {!! Form::label('back_dies','Back Dies') !!}

                @if(isset($coin->back_dies_type))
                    @if($coin->back_dies_type == 'Location Dies')

                        <select name="back_dies" id="back_dies" class="form-control">
                            <option value="">Please Select</option>
                            @foreach($location_dies as $dies)
                                <option
                                        value="{{ $dies->id }}"
                                        data-imagesrc="{{ $dies->photo}}"
                                        {{ ($dies->id == $coin->back_dies ? 'selected':'') }}
                                        >{{$dies->name}}</option>

                            @endforeach
                        </select>
                    @else
                        <select name="back_dies" id="back_dies" class="form-control">
                            <option value="">Please Select</option>
                            @foreach($stock_dies as $dies)
                                <option
                                        value="{{ $dies->id }}"
                                        data-imagesrc="{{ $dies->photo}}"
                                        {{ ($dies->id == $coin->back_dies ? 'selected':'') }}
                                        >{{$dies->name}}
                                </option>

                            @endforeach
                        </select>
                    @endif
                @else
                    {!! Form::select('back_dies',array(),null,array('class'=>'form-control') ) !!}
                @endif



                @if(isset($coin->metal))
                    <div class="dies back {!! strtolower($coin->metal) !!}">
                        <img src="/upload/100-{!! $coin->back_dies()->photo !!}">

                    </div>
                @else
                    <div class="dies back brass">		</div>
                @endif



            </div>
        </div>

    </div>

</div>

<div class="form-group">
    @if(Request::is('admin/coins/*/edit'))
        <a href="{{ URL::route('admin.coins.show', $coin->id) }}" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Cancel</a>
    @elseif(Request::is('admin/coins/create'))
        <a href="{{ URL::route('admin.coins.index') }}" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Cancel</a>
    @endif
    {!! Form::submit($submit_btn_text,['class'=>'btn btn-primary']) !!}
</div>

resources/views/admin/coins/index.blade.php
@extends('admin.layout')
@section('title','Coins')

@section('main')
    <h1 class="page-header">Coins
        <a href="{{URL::to('admin/coins/create')}}" class="btn btn-sm btn-primary pull-right">
            <i class="glyphicon glyphicon-plus"></i> Add New Coin
        </a>
    </h1>

    @if($coins->isEmpty() )

        <p class="alert alert-warning">
            No coins found! Please
            <a href="{{ url('admin/coins/create')}}">create a coin</a>
        </p>

    @else
        <table class="table table-striped table-bordered coins table_sortable">
            <thead>
                <tr>
                    <th>SL</th>
                    <th>Name</th>
                    {{--<th>Front Die</th>--}}
                    {{--<th>Back Die</th>--}}
                    <th>Location</th>
                    <th>Top Inventory</th>
                    <th>Inventory</th>
                    <th>Metal</th>
                    <th>Finish</th>
                    <th>Notes</th>
                    <th>Action</th>
                </tr>
            </thead>
            @foreach($coins as $index=>$coin)
                <tr>
                    <td>{{$index+1}}</td>
                    <td>{{$coin->name}}</td>
                    {{--<td>

                        {!! Html::image('upload/50-'.$coin->front_dies()->photo, $coin->front_dies()->photo, array('class' => 'dies_photo thumb pull-left')) !!}

                        {{$coin->front_dies()->name}}

                        <p title="cabinet drawer row col">{{ $coin->front_dies()->cabinet.' '.$coin->front_dies()->drawer.' '.$coin->front_dies()->row.' '.$coin->front_dies()->col}}</p>

                    </td>

                    <td>

                        {!! Html::image('upload/50-'.$coin->back_dies()->photo, $coin->back_dies()->photo, array('class' => 'dies_photo thumb pull-left')) !!}

                        {{$coin->back_dies()->name}}

                        <p title="cabinet drawer row col">{{ $coin->back_dies()->cabinet.' '.$coin->back_dies()->drawer.' '.$coin->back_dies()->row.' '.$coin->back_dies()->col}}</p>

                    </td>--}}

                    <td>
                        <a href="{{ URL::route('admin.locations.show',$coin->location->id) }}">{{ $coin->location->name }}</a>
                    </td>
                    <td>{{$coin->top_inventory}}</td>
                    <td>{{$coin->inventory}}</td>
                    <td>{{$coin->metal}}</td>
                    <td>{{$coin->finish}}</td>
                    <td>{{$coin->notes}}</td>

                    <td>

                        <a href="{{ URL::route('admin.coins.edit',$coin->id) }}" class="btn btn-xs btn-info"><i class="glyphicon glyphicon-edit"></i> Edit</a>&nbsp;&nbsp;
                        <a title="delete" data-url="{{url('admin/coins/'.$coin->id)}}" data-token="{{csrf_token()}}" class="admin_coin_del_btn btn btn-xs btn-danger" href="#"><i class="glyphicon glyphicon-trash"></i> Delete</a>

                    </td>

                </tr>
            @endforeach
        </table>

    @endif

@stop


@section('script')
    @include('admin.coins.script')
@stop

resources/views/admin/coins/script.blade.php
<script type="text/javascript">
    $(document).ready(function() {


	    /**
         * delete coin from coins.show
         */

        $('.admin_coin_del_btn').click(function (e) {
            e.preventDefault();

            var target = $(this);
            var url = $(this).data('url');
            var token = $(this).data('token');

            alertify.confirm('Are you sure you want to delete this Coin ? This action cannot be undone.').setting({
                'title': '<span class="glyphicon glyphicon-trash"></span> Delete Coin',
                'labels': {ok: 'DELETE'},
                'onok': function () {

                    $.ajax({

                        url: url,
                        type: 'POST',
                        data: {_method: 'delete', _token: token},

                        beforeSend: function () {

                            $(target).addClass('disabled');
                            $(target).parent().parent().css('opacity', '.5');

                        },
                        success: function (res) {

                            if (res == 'success') {

                                $('.nav-sidebar .badge.coins').html(parseInt($('.nav-sidebar .badge.coins').html()) - 1);

                                $(target).parent().parent().fadeOut(500, function () {
                                    $(target).parent().parent().remove();
                                });

                                alertify.success('Coin has been deleted');

                            } else {

                                $(target).removeClass('disabled');
                                $(target).parent().parent().css('opacity', '1');
                                alertify.error('Failed to delete Coin. <br>' + res);
                            }


                        }
                    });


                },
                'oncancel': function () {


                }
            });
        });

        $('#metal').change(function () {
            var selected_metal = $(this).val();
            $('form .dies').removeClass('brass copper nickel_silver');

            if (selected_metal == 'Brass') {
                $('form .dies').addClass('brass');
            } else if (selected_metal == 'Copper') {
                $('form .dies').addClass('copper');
            } else if (selected_metal == 'Nickel Silver') {
                $('form .dies').addClass('nickel_silver');
            }

        });


        window.update_front_dies_list = function (location_id) {

            if ($('select#front_dies_type').val() == 'Stock Dies') {
                location_id = 0;
            }

            $.ajax({
                url: '/admin/get_dies/' + location_id,
                type: 'GET',
                beforeSend: function () {
                    $('select#front_dies').addClass('loading');
                },
                success: function (res) {
                    $('select#front_dies').removeClass('loading');
                    $('select#front_dies option').remove();
                    $('select#front_dies').append("<option value=''>Please Select</option>");

                    $.each(res, function (index, dies) {

                        $('<option/>', {
                            text: dies.name,
                            value: dies.id,
                            data: {
                                imagesrc: dies.photo
                            }
                        }).appendTo('select#front_dies');


                    });


                    var old_front_dies = '<?php echo \Input::old('front_dies');?>';
                    $('select#front_dies').val(old_front_dies);

                    if ($('select#front_dies').find(':selected').val() != '') {
                        $('.dies.front').html('<img alt=" " src="/upload/100-' + $('select#front_dies').find(':selected').data('imagesrc') + '">');
                    }


                }
            });
        }

        window.update_back_dies_list = function (location_id) {

            if ($('select#back_dies_type').val() == 'Stock Dies') {
                location_id = 0;
            }

            $.ajax({
                url: '/admin/get_dies/' + location_id,
                type: 'GET',
                beforeSend: function () {
                    $('select#back_dies').addClass('loading');
                },
                success: function (res) {
                    $('select#back_dies').removeClass('loading');
                    $('select#back_dies option').remove();
                    $('select#back_dies').append("<option value=''>Please Select</option>");


                    $.each(res, function (index, dies) {

                        $('<option/>', {
                            text: dies.name,
                            value: dies.id,
                            data: {
                                imagesrc: dies.photo

                            }
                        }).appendTo('select#back_dies');


                    });

                    var old_back_dies = '<?php echo \Input::old('back_dies');?>';
                    $('select#back_dies').val(old_back_dies);

                    if ($('select#back_dies').find(':selected').val() != '') {
                        $('.dies.back').html('<img alt=" " src="/upload/100-' + $('select#back_dies').find(':selected').data('imagesrc') + '">');
                    }

                }
            });


        }


        $('select#location_id').change(function () {
            var location_id = $('select#location_id').val();
            if (location_id != '') {
                update_front_dies_list(location_id);
                update_back_dies_list(location_id);
            }
        });

        $('select#front_dies_type').change(function () {
            var location_id = $('select#location_id').val();
            if (location_id != '') {
                update_front_dies_list(location_id);
            }
        });

        $('select#back_dies_type').change(function () {
            var location_id = $('select#location_id').val();
            if (location_id != '') {
                update_back_dies_list(location_id);
            }
        });

        $('select#front_dies').change(function () {

            if ($(this).find(':selected').val() != '') {
                $('.dies.front').html('<img src="/upload/100-' + $(this).find(':selected').data('imagesrc') + '">');
            }

        });

        $('select#back_dies').change(function () {

            if ($(this).find(':selected').val() != '') {
                $('.dies.back').html('<img src="/upload/100-' + $(this).find(':selected').data('imagesrc') + '">');
            }

        });
    });

</script>